<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'nsqphp' => array($vendorDir . '/henter/nsqphp/src'),
    'Prophecy\\' => array($vendorDir . '/phpspec/prophecy/src'),
    'Pimple' => array($vendorDir . '/pimple/pimple/src'),
    'PhpSpec' => array($vendorDir . '/phpspec/phpspec/src'),
    'PHPExcel' => array($vendorDir . '/phpoffice/phpexcel/Classes'),
    'Mockery' => array($vendorDir . '/mockery/mockery/library'),
    'Maatwebsite\\Excel\\' => array($vendorDir . '/maatwebsite/excel/src'),
    'JakubOnderka\\PhpConsoleHighlighter' => array($vendorDir . '/jakub-onderka/php-console-highlighter/src'),
    'JakubOnderka\\PhpConsoleColor' => array($vendorDir . '/jakub-onderka/php-console-color/src'),
    'Imagine' => array($vendorDir . '/imagine/imagine/lib'),
    'Evenement' => array($vendorDir . '/evenement/evenement/src'),
    'Doctrine\\Common\\Inflector\\' => array($vendorDir . '/doctrine/inflector/lib'),
    'Diff' => array($vendorDir . '/phpspec/php-diff/lib'),
    'Dflydev\\ApacheMimeTypes' => array($vendorDir . '/dflydev/apache-mime-types/src'),
    'Curl' => array($vendorDir . '/curl/curl/src'),
    'Colors' => array($vendorDir . '/kevinlebrun/colors.php/src'),
    'Barryvdh' => array($vendorDir . '/barryvdh/reflection-docblock/src'),
);
