<?php

namespace Slion\DB\Vo;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-08-09 at 17:26:42.
 */
class BlockTest extends \PHPUnit_Framework_TestCase {

    static $data;

    /**
     * @var Block
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $vo = new class() extends \Slion\DB\Vo {
            protected static $_default = [
                'id'      => null,
                'name'    => 'worker',
                'age'     => null,
            ];
        };
        $this->object = $vo::makeBlock(2, 3);

        self::$data = [];
        for ($i = 0; $i < 10; $i++) {
            self::$data[] = [
                'id'    => mt_rand(1000, 9999),
                'age'   => mt_rand(30, 40),
            ];
        }
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers Slion\DB\Vo\Block::setIdField
     * @todo   Implement testSetIdField().
     */
    public function testSetIdField() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Slion\DB\Vo\Block::offset
     * @todo   Implement testOffset().
     */
    public function testOffset() {
        $this->assertEquals(2, $this->object->offset());
    }

    /**
     * @covers Slion\DB\Vo\Block::limit
     * @todo   Implement testLimit().
     */
    public function testLimit() {
        $this->assertEquals(3 + 1, $this->object->limit());
    }

    /**
     * @covers Slion\DB\Vo\Block::__invoke
     * @todo   Implement test__invoke().
     */
    public function test__invoke() {
        $block  = $this->object;
        $result = $block(self::$data);
//        du($result);
    }

    /**
     * @covers Slion\DB\Vo\Block::fill
     * @todo   Implement testFill().
     */
    public function testFill() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Slion\DB\Vo\Block::toArray
     * @todo   Implement testToArray().
     */
    public function testToArray() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}
